version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd server
      - npm install
  build:
    commands:
      - echo Packaging application...
      - zip -r app.zip .  # Compress all files into app.zip in the current directory

artifacts:
  files:
    - app.zip  # Specify the file to be output as an artifact
