version: 0.2

phases:
  install:
    commands:
      - cd backend
      - echo Installing Node.js dependencies...
      - npm install
  post_build:
    commands:
      - echo Starting the application...
      - node server.js

artifacts:
  files:
    - '**/*'
