version: 0.2

phases:
  install:
    commands:
      - cd server
      - npm install
  build:
    commands:
      - npm run build  # Optional, if you have a build step
artifacts:
  files:
    - '**/*'           # Include all files from the build
  base-directory: server # Specify the directory to include in the artifact
  discard-paths: no
