version: 0.2

phases:
  install:
    commands:
      - cd backend   # or wherever `app.js` resides
      - npm install
  build:
    commands:
      - node app.js   # Run the app from the correct location
